### ISSUE TITLE
getFrameFromSeconds() ignores parameter; always passes same position argument to ffmpeg

### ISSUE THREAD

**Issue by TheOneTrueLX** [pascalbaljetmedia/laravel-ffmpeg#102] opened 2018-08-21 15:08 UTC
The getFrameFromSeconds() function does not appear to be working as expected.  No matter what value is passed to this function as a parameter, this function will always pass a value of '04:21:40.00' to the ffmpeg command.

Example from my code:

```
$media->getFrameFromSeconds(1)
    ->export()
    ->toDisk('public')
    ->save('videos/' . $filename . '_frame.png');
```

And the result from the Laravel logs:

```
[2018-08-21 14:31:34] local.INFO: ffmpeg running command '/usr/bin/ffmpeg' '-y' '-ss' '04:21:40.00' '-i' '<obfuscated>/storage/app/public/images/l9wNqItZ6Gkqm8H2izeqxDA18HV52KgqwFuzloTk.mp4' '-vframes' '1' '-f' 'image2' '<obfuscated>/storage/app/public/videos/l9wNqItZ6Gkqm8H2izeqxDA18HV52KgqwFuzloTk_frame.png'
[2018-08-21 14:31:34] local.INFO: ffmpeg executed command successfully
```

In this particular case, since the video in question is only 30-ish seconds long, no frame is ever grabbed and the .png is never generated.  Originally I was trying to do some clever math to pass to the function as an argument, but only once I dug into the logs did I notice that ffmpeg was consistently being called with the '04:21:40.00' position argument regardless of what value I passed to getFrameFromSeconds().

For what it's worth, getFrameFromString() works just fine.  I haven't tested getFrameFromTimecode().

**Comment by pascalbaljet** [comment] 2018-09-03 18:39
I can't reproduce the bug, can you post the code that calls the `getFrameFromSeconds` method?

**Comment by jason-guru** [comment] 2019-05-29 12:04
In my case this issue is only on linux operating system, on windows it's working fine. Can anyone please help me with a solution for this?

**Comment by pascalbaljet** [comment] 2020-05-28 11:32
I'm closing this issue as I can't reproduce it with the given example. I guess there's some kind of rounding error in your code.

**Closed by pascalbaljet** 2020-05-28 11:32 UTC
