### ISSUE TITLE
Update for Laravel 5.6

### ISSUE THREAD

**Issue by francoism90** [pascalbaljetmedia/laravel-ffmpeg#65] opened 2018-02-08 13:38 UTC
Thanks!

**Comment by sullyfischer** [comment] 2018-02-16 15:27
+1

**Comment by uschmann** [comment] 2018-02-17 15:16
I think the problem is related to 
php-ffmpeg.

**Comment by liucf** [comment] 2018-02-19 10:50
@pascalbaljet why it  not working for Laravel 5.6?  will it work in the future?

**Comment by pascalbaljet** [comment] 2018-02-19 21:30
Version 2.0.0 has been released with Support for Laravel 5.6!

**Closed by pascalbaljet** 2018-02-19 21:30 UTC
