### ISSUE TITLE
Convert inFormat X264 with different audio codec instead of (libfdk_)aac?

### ISSUE THREAD

**Issue by Jaspur** [pascalbaljetmedia/laravel-ffmpeg#116] opened 2018-11-09 15:06 UTC
Hi @pascalbaljet ,
I'm getting this error on Ubuntu: ```Unknown encoder 'libfdk_aac'```, because Ubuntu doesn't work with that codec for audio (found on Google).

But how can I convert my video with a different audio codec?
```
FFMpeg::fromDisk('local')
            ->open('videos/0.qt')
            ->export()
            ->toDisk('local')
            ->inFormat(new \FFMpeg\Format\Video\X264())
            ->save('videos/0.mp4');
```

**Comment by pascalbaljet** [comment] 2018-11-09 15:11
Duplicate of https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/13

**Closed by pascalbaljet** 2018-11-09 15:11 UTC
