### ISSUE TITLE
A non-numeric value encountered - AbstractProgressListener

### ISSUE THREAD

**Issue by ojsoft** [pascalbaljetmedia/laravel-ffmpeg#6] opened 2017-02-02 20:31 UTC
When encoding uploaded videos i always run into an error exception:

#Code used

`    
    $lowBitrate = (new X264('libmp3lame'))->setKiloBitrate(250);
    $midBitrate = (new X264('libmp3lame'))->setKiloBitrate(500);
    $highBitrate = (new X264('libmp3lame'))->setKiloBitrate(1000);

    FFMpeg::fromDisk('public')->open($video)->exportForHLS()
        ->setSegmentLength(10)
        ->addFormat($lowBitrate)
        ->addFormat($midBitrate)
        ->addFormat($highBitrate)
        ->save($filename . '.m3u8');
`

#Stack Crawl

`[2017-02-02 12:47:39] local.INFO: ffmpeg running command '/usr/local/bin/ffmpeg' '-y' '-i' '/Users/oj/code/kinklink/storage/app/public/users/1/upload/p3Anee5RoWmd-1.mp4' '-map' '0' '-flags' '-global_header' '-f' 'segment' '-segment_format' 'mpeg_ts' '-segment_list' '/Users/oj/code/kinklink/storage/app/public/users/1/content/p3Anee5RoWmd-1_250.m3u8' '-segment_time' '10' '-threads' '12' '-vcodec' 'libx264' '-acodec' 'libmp3lame' '-b:v' '250k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-pass' '1' '-passlogfile' '/var/folders/g_/b9xjq9yx6859bxwchm6tqp0c0000gr/T/ffmpeg-passes58932a6b4a6acfitu5/pass-58932a6b4a77e' '/content/p3Anee5RoWmd-1_250_%05d.ts'  
[2017-02-02 12:47:40] local.ERROR: ErrorException: A non-numeric value encountered in /Users/oj/code/kinklink/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Format/ProgressListener/AbstractProgressListener.php:182
Stack trace:
#0 /Users/oj/code/kinklink/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Format/ProgressListener/AbstractProgressListener.php(182): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'A non-numeric v...', '/Users/oj/code/...', 182, Array)
#1 /Users/oj/code/kinklink/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Format/ProgressListener/AbstractProgressListener.php(136): FFMpeg\Format\ProgressListener\AbstractProgressListener->parseProgress('frame=  659 fps...')
#2 /Users/oj/code/kinklink/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(90): FFMpeg\Format\ProgressListener\AbstractProgressListener->handle('err', 'frame=  659 fps...')
#3 [internal function]: Alchemy\BinaryDriver\ProcessRunner->Alchemy\BinaryDriver\{closure}('err', 'frame=  659 fps...')
#4 /Users/oj/code/kinklink/vendor/symfony/process/Process.php(1345): call_user_func(Object(Closure), 'err', 'frame=  659 fps...')
#5 /Users/oj/code/kinklink/vendor/symfony/process/Process.php(1450): Symfony\Component\Process\Process->Symfony\Component\Process\{closure}('err', 'frame=  659 fps...')
`

Thanks a lot for looking into the problem...

**Comment by pascalbaljet** [comment] 2017-02-06 20:05
Could you post the your `filesystem.php` config file? It looks like something is wrong with your output path.

**Comment by ojsoft** [comment] 2017-02-06 21:01
I do not believe that this will help. The problem occures on my local machine the same way than on the forge staging server.

`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Filesystem Disk
    |--------------------------------------------------------------------------
    |
    | Here you may specify the default filesystem disk that should be used
    | by the framework. The "local" disk, as well as a variety of cloud
    | based disks are available to your application. Just store away!
    |
    */

    'default' => 'local',

    /*
    |--------------------------------------------------------------------------
    | Default Cloud Filesystem Disk
    |--------------------------------------------------------------------------
    |
    | Many applications store files both locally and in the cloud. For this
    | reason, you may specify a default "cloud" driver here. This driver
    | will be bound as the Cloud disk implementation in the container.
    |
    */

    'cloud' => 's3',

    /*
    |--------------------------------------------------------------------------
    | Filesystem Disks
    |--------------------------------------------------------------------------
    |
    | Here you may configure as many filesystem "disks" as you wish, and you
    | may even configure multiple disks of the same driver. Defaults have
    | been setup for each driver as an example of the required options.
    |
    | Supported Drivers: "local", "ftp", "s3", "rackspace"
    |
    */

    'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => 'your-key',
            'secret' => 'your-secret',
            'region' => 'your-region',
            'bucket' => 'your-bucket',
        ],

    ],

];
`

**Comment by ojsoft** [comment] 2017-02-06 21:04
version: 1.1.4

**Comment by jenky** [comment] 2017-02-07 03:06
I got the same error

**Comment by pascalbaljet** [comment] 2017-02-21 09:14
I can't reproduce the error, might it be possible to send me the video?

**Comment by ojsoft** [comment] 2017-02-23 07:28
Hello Pascal,
I tried with several mp4 videos, I get this problem always and every time.

Here is one of those test videos for download:

http://www.ojsoft.de/TestVideo.mp4

**Comment by pascalbaljet** [comment] 2017-03-20 22:08
Could you also upload the FFMpeg log? (not the PHP output but the ffmpeg/ffprobe stuff). And what is the value of ```$filename```?

Sorry for the delay btw!

**Comment by nsbeyond** [comment] 2017-03-31 03:31
`[2017-03-31 03:25:03] local.INFO: ffprobe running command '/usr/local/bin/ffprobe' '-help' '-loglevel' 'quiet'  
[2017-03-31 03:25:03] local.INFO: ffprobe executed command successfully  
[2017-03-31 03:25:03] local.INFO: ffprobe running command '/usr/local/bin/ffprobe' '/var/www/app/storage/videos/small.mp4' '-show_streams' '-print_format' 'json'  
[2017-03-31 03:25:03] local.INFO: ffprobe executed command successfully  
[2017-03-31 03:25:03] local.INFO: ffmpeg running command '/usr/local/bin/ffmpeg' '-y' '-i' '/var/www/app/storage/videos/small.mp4' '-map' '0' '-flags' '-global_header' '-f' 'segment' '-segment_format' 'mpeg_ts' '-segment_list' '/var/www/app/storage/videos/1490930703_250.m3u8' '-segment_time' '10' '-threads' '12' '-vcodec' 'libx264' '-acodec' 'libfaac' '-b:v' '250k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes58ddcc0f90782t3y7n/pass-58ddcc0f9087c' '/var/www/app/storage/videos/1490930703_250_%05d.ts'  
[2017-03-31 03:25:03] local.INFO: ffprobe running command '/usr/local/bin/ffprobe' '/var/www/app/storage/videos/small.mp4' '-show_format' '-print_format' 'json'  
[2017-03-31 03:25:03] local.INFO: ffprobe executed command successfully  
[2017-03-31 03:25:03] local.ERROR: ffmpeg failed to execute command '/usr/local/bin/ffmpeg' '-y' '-i' '/var/www/app/storage/videos/small.mp4' '-map' '0' '-flags' '-global_header' '-f' 'segment' '-segment_format' 'mpeg_ts' '-segment_list' '/var/www/app/storage/videos/1490930703_250.m3u8' '-segment_time' '10' '-threads' '12' '-vcodec' 'libx264' '-acodec' 'libfaac' '-b:v' '250k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes58ddcc0f90782t3y7n/pass-58ddcc0f9087c' '/var/www/app/storage/videos/1490930703_250_%05d.ts'  
[2017-03-31 03:25:03] local.ERROR: Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command '/usr/local/bin/ffmpeg' '-y' '-i' '/var/www/app/storage/videos/small.mp4' '-map' '0' '-flags' '-global_header' '-f' 'segment' '-segment_format' 'mpeg_ts' '-segment_list' '/var/www/app/storage/videos/1490930703_250.m3u8' '-segment_time' '10' '-threads' '12' '-vcodec' 'libx264' '-acodec' 'libfaac' '-b:v' '250k' '-refs' '6' '-coder' '1' '-sc_threshold' '40' '-flags' '+loop' '-me_range' '16' '-subq' '7' '-i_qfactor' '0.71' '-qcomp' '0.6' '-qdiff' '4' '-trellis' '1' '-b:a' '128k' '-pass' '1' '-passlogfile' '/tmp/ffmpeg-passes58ddcc0f90782t3y7n/pass-58ddcc0f9087c' '/var/www/app/storage/videos/1490930703_250_%05d.ts' in /var/www/app/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:100
`

This FFMPeg log Thanks you

**Comment by ysk99** [comment] 2017-07-08 11:05
can you tell me how to config the three paraments??1. filesystems 2.config 3.logger
```
public function convmp3()
    {
        $new = New FFMpeg('','','');


    }
```

**Comment by pascalbaljet** [comment] 2017-08-30 12:08
I'll close this issue since there hasn't been any activity for nearly 5 months.

**Closed by pascalbaljet** 2017-08-30 12:08 UTC

**Comment by pzanwar03** [comment] 2021-01-21 18:59
I got the same error. Have any solution?
