### ISSUE TITLE
AAC Experimental

### ISSUE THREAD

**Issue by andylord56** [pascalbaljetmedia/laravel-ffmpeg#154] opened 2019-10-08 12:00 UTC
Getting:

``
The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
``
When using 
`$lowBitrateFormat  = (new X264('aac'))->setKiloBitrate(150); `

How do I get this to run ?

**Comment by shahzadwaris** [comment] 2019-10-13 17:16
This is my code and it is working try it.
```
$low = (new X264('aac'))->setKiloBitrate(100);
        FFMpeg::fromDisk('local')
            ->open("public\\videos\\" . $this->video->videoLink)
            ->exportForHLS()
            ->addFormat($low)
->save("public/videos/{$this->video->id}" . '.m3u8');
```

**Comment by pascalbaljet** [comment] 2019-10-21 11:35
Your FFmpeg build is probably missing support for AAC. Duplicate of https://github.com/pascalbaljetmedia/laravel-ffmpeg/issues/13

**Closed by pascalbaljet** 2019-10-21 11:35 UTC
