### ISSUE TITLE
FFMpeg \ Exception \ ExecutableNotFoundException Unable to load FFProbe

### ISSUE THREAD

**Issue by rajupaul** [pascalbaljetmedia/laravel-ffmpeg#111] opened 2018-09-23 08:26 UTC
`return [
    'default_disk' => 'local',

    'ffmpeg' => [
        'binaries' => env('FFMPEG_BINARIES', 'C:/FFmpeg/bin/ffmpeg.exe'),
        'threads' => 12,
    ],

    'ffprobe' => [
        'binaries' => env('FFPROBE_BINARIES', 'C:/FFmpeg/bin/ffprobe.exe'),
    ],

    'timeout' => 3600,
];`

above is my config for ffmpeg
and i placed the FFmpeg Builds in C:/FFmpeg/  .help me for the solution

**Comment by 4unkur** [comment] 2018-10-26 06:18
I added 2 values in config file:

```
    'ffmpeg.binaries' => env('FFMPEG_BINARIES', 'ffmpeg'),

    'ffprobe.binaries' => env('FFMPEG_BINARIES', 'ffprobe'),
```
The issue is:
It tries to load config values like this:

```
        $binaries = $configuration->get('ffprobe.binaries', array('avprobe', 'ffprobe'));

```
and get method is:

```
    public function get($key, $default = null)
    {
        return isset($this->data[$key]) ? $this->data[$key] : $default;
    }
```

So there is no `ffmpeg.binaries` & `ffprobe.binaries` keys...

@pascalbaljet

**Comment by RichPC** [comment] 2018-11-08 13:38
As @4unkur pointed out the correct path to the binary isn't loaded from the configuration file.

So the code then falls back on using a 'finder' object to look for 'ffprobe'. The finder object works it's way through php's open_basedir directories. This resulted in the code working on my local docker container but not on my production Ubuntu 18.04 setup because the open_basedir settings where different.

**Comment by pascalbaljet** [comment] 2018-11-09 17:20
A recent PR broke the config loader, should be fixed now:
https://github.com/pascalbaljetmedia/laravel-ffmpeg/releases/tag/3.0.2

**Closed by pascalbaljet** 2018-11-09 17:20 UTC
